#Prometheus yaml file is used to configure the prometheus instance running in the docker image. 
#We define some basic values

global: 
  scrape_interval: 15s #Default scraping interval, where prometheus will scrape values from its targets. 
   

scrape_configs: 
  #We want at least one job to target itself. 
  - job_name: 'prometheus'
    scrape_interval: 5s 
    static_configs: 
      - targets: ['localhost:9090'] #this is localhost, because it is running in local host 

  - job_name: 'moon-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2m
    scrape_timeout: 1m
    static_configs: 
      - targets: ['consumer:8020'] # Moon is referencing the label we gave it in docker compose file. 
        #Because prometheus and the services are in the same bridge network

