server:
  port: 7700

#In docker compose we can't use the default "http://localhost:8500" for consul
#Instead we need to specify it ourselves
#apring.cloud.consul.host=<domain>

spring:
  h2:
    console: 
      enabled: true
      path: /h2
  datasource: 
    url: jdbc:h2:mem:moondb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true 
  application:
    name: Moon-Service
  cloud:
    consul:
      host: http://discovery #In docker compose, this will look for a service labelled "consul"
      port: 8500

management:
  endpoints:
    web:
      exposure:
        include:
        - prometheus
        - info
        - health