server:
  port: 7700


spring:
  h2:
    console: 
      enabled: true
      path: /h2
  datasource: 
    url: jdbc:h2:mem:moondb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true 
  application:
    name: Moon-Service
    
management:
  endpoints:
    web:
      exposure:
        include:
        - prometheus
        - info
        - health