server:
  port: 8700


spring:
  h2:
    console: 
      enabled: true
      path: /h2
  datasource: 
    url: jdbc:h2:mem:planetdb
    username: sun
    password: 
    driverClassName: org.h2.Driver
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true 
  application:
    name: Planet-Service

  config:
    import:
    - optional:configserver:http://localhost:8888
  profiles:
    active:
    - dev
  cloud:
    consul:
      host: http://discovery #In docker compose, this will look for a service labelled "consul"
      port: 8500    

management:
  endpoints:
    web:
      exposure:
        include:
        - prometheus
        - info
        - health